#!/bin/sh

cloc $PWD --fullpath --not-match-f="(^.*build.*$)|(^.*googletest.*$)" -quiet --md >> $PWD/cloc.md
embed-markdown $PWD/real_readme.md $PWD/README.md
rm $PWD/cloc.md
git add $PWD/README.md
exit 0
