version: "3.9"
services:
  database:
    image: "postgres:15.2"
    ports:
      - "5432:5432"
    volumes:
      - sdi-postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DATABASE_USERNAME}"]
      interval: 5s
      timeout: 3s
      retries: 3
  liquibase:
    image: "liquibase/liquibase:4.20"
    depends_on:
      database:
        condition: service_healthy
    volumes:
      - ./src/main/resources/db/changelog/:/liquibase/changelog/
    env_file:
      - .env
    environment:
      - LIQUIBASE_COMMAND_URL=${DATABASE_DRIVER}://database:5432/main
      - LIQUIBASE_COMMAND_USERNAME=${DATABASE_USERNAME}
      - LIQUIBASE_COMMAND_PASSWORD=${DATABASE_PASSWORD}
      - LIQUIBASE_COMMAND_CHANGELOG_FILE=db.changelog-master.yaml
      - LIQUIBASE_COMMAND_TAG=${TARGET_TAG}
    command:
      - update-to-tag
  ai:
    build: ../ai-microservice/
    ports:
      - "5000:5000"

volumes:
  sdi-postgres:
    external: true