wandb_version: 1

NUM_EPOCHS:
  desc: null
  value: 30
BATCH_SIZE:
  desc: null
  value: 48
INPUT_SHAPE:
  desc: null
  value:
  - 128
  - 128
NUM_LAYERS:
  desc: null
  value: 2
LR:
  desc: null
  value: 0.004
INTERMEDIARY_FILTERS:
  desc: null
  value: 32
OPTIMIZER:
  desc: null
  value: Adam
_wandb:
  desc: null
  value:
    python_version: 3.9.1
    cli_version: 0.16.2
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1705160302.366558
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 16
      - 23
      4: 3.9.1
      5: 0.16.2
      8:
      - 1
      - 3
      - 5
      13: windows-amd64
