[package]
name = "lab5"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.3.29"
rand = "0.8.5"
rayon = "1.8.0"
rayon-join-macro = "0.1.1"
